export const dynamic = 'force-dynamic';
export const maxDuration = 30;

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { INK_COSTS } from '@/lib/types';

export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { storyId } = await request.json();
    if (!storyId) {
      return NextResponse.json({ error: 'Story ID is required' }, { status: 400 });
    }

    const story = await prisma.story.findUnique({ where: { id: storyId } });
    if (!story || story.userId !== session.user.id) {
      return NextResponse.json({ error: 'Story not found' }, { status: 404 });
    }

    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: { inks: true },
    });

    const cost = INK_COSTS.exportPdf;
    if (!user || (user?.inks ?? 0) < cost) {
      return NextResponse.json({ error: `Not enough Inks. Need: ${cost}` }, { status: 402 });
    }

    const contentParagraphs = (story.content ?? '')
      .split('\n').filter((p) => p.trim())
      .map((p) => `<p style="margin-bottom:1em;line-height:1.8;font-size:14px;color:#333;">${p.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p>`)
      .join('');

    const htmlContent = `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Georgia,serif;margin:0;padding:40px;background:#fff;}.header{text-align:center;margin-bottom:40px;border-bottom:2px solid #e5e7eb;padding-bottom:24px;}.title{font-size:28px;font-weight:700;color:#1a1a2e;margin:0 0 8px;}.meta{font-size:12px;color:#9ca3af;}.content{max-width:600px;margin:0 auto;}.footer{margin-top:40px;text-align:center;font-size:11px;color:#d1d5db;border-top:1px solid #e5e7eb;padding-top:16px;}</style></head><body><div class="header"><h1 class="title">${story.title.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</h1><div class="meta">${(story.genre ?? '').replace('-', ' ').toUpperCase()} &bull; Created with VibeScribe</div></div><div class="content">${contentParagraphs}</div><div class="footer">Generated by VibeScribe</div></body></html>`;

    let browser;
    try {
      const chromium = (await import('@sparticuz/chromium')).default;
      const puppeteer = (await import('puppeteer-core')).default;
      browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath(),
        headless: true,
      });

      const page = await browser.newPage();
      await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
      const pdfBuffer = await page.pdf({ format: 'A4', margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' }, printBackground: true });

      await prisma.$transaction([
        prisma.user.update({ where: { id: session.user.id }, data: { inks: { decrement: cost } } }),
        prisma.transaction.create({ data: { userId: session.user.id, amount: -cost, type: 'SPEND', description: 'PDF export' } }),
      ]);

      return new NextResponse(Buffer.from(pdfBuffer) as unknown as BodyInit, {
        headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="${story.title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf"` },
      });
    } finally {
      if (browser) await browser.close();
    }
  } catch (error: any) {
    console.error('PDF export error:', error);
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}
